//! Aider `.aider.conf.yml` snippet formatter.
//!
//! Aider reads a YAML config from `.aider.conf.yml` at the project root.
//! There is no first-class "skill" concept; instead we emit a snippet that
//! sets `read` to include a markdown tool guide (also generated in-band as a
//! YAML literal block scalar) so Aider injects the guidance into its system
//! prompt on every session.

use crate::skills::tools::ToolMetadata;
use crate::skills::{SKILL_INTRO, SKILL_TAGLINE};
use serde::Serialize;

#[derive(Serialize)]
struct AiderSnippet {
    // Aider top-level keys; only the ones we care about.
    #[serde(rename = "read")]
    read: Vec<String>,
    #[serde(rename = "lint-cmd")]
    lint_cmd: Option<String>,
    /// Free-form description of semantex for the operator who's merging this.
    #[serde(rename = "_semantex_about")]
    about: String,
    /// Full markdown rules body, embedded so Aider can include it via `read`
    /// or the operator can extract it.
    #[serde(rename = "_semantex_rules")]
    rules: String,
}

pub fn render(tools: &[ToolMetadata]) -> String {
    let snippet = AiderSnippet {
        read: vec![".aider/semantex.md".into()],
        lint_cmd: None,
        about: SKILL_TAGLINE.into(),
        rules: render_rules_md(tools),
    };

    // `serde_yml` produces a valid YAML document. We prepend a comment header
    // explaining how to use the snippet.
    let body = serde_yml::to_string(&snippet).expect("aider snippet serialises");
    let mut out = String::new();
    out.push_str(
        "# .aider.conf.yml — semantex snippet (generated by `semantex skills-generate`).\n",
    );
    out.push_str(
        "# Merge these keys into your project's `.aider.conf.yml`, and write the value of\n",
    );
    out.push_str(
        "# `_semantex_rules` to `.aider/semantex.md` so Aider picks it up via the `read` list.\n",
    );
    out.push_str("# `_semantex_*` keys are unknown to Aider and exist only for the operator.\n\n");
    out.push_str(&body);
    out
}

fn render_rules_md(tools: &[ToolMetadata]) -> String {
    let mut out = String::new();
    out.push_str("# semantex — semantic code search rules for Aider\n\n");
    out.push_str(SKILL_INTRO);
    out.push_str("\n\n");
    out.push_str(concat!(
        "Prefer `semantex_agent` for any code search question. One call replaces 5–10 grep + ",
        "read iterations.\n\n",
    ));
    out.push_str("## Tools\n\n");
    out.push_str(&super::render_tools_md(tools));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::skills::tools::all_tools;

    #[test]
    fn parses_as_valid_yaml() {
        let tools = all_tools();
        let out = render(&tools);
        // Strip the leading `#` comment block before parsing as YAML.
        let yaml_start = out
            .lines()
            .position(|l| !l.starts_with('#') && !l.trim().is_empty())
            .expect("YAML body should start after the comment header");
        let yaml_body = out.lines().skip(yaml_start).collect::<Vec<_>>().join("\n");
        let value: serde_yml::Value =
            serde_yml::from_str(&yaml_body).expect("aider snippet must be valid YAML");
        // Top-level should be a mapping with `read`.
        assert!(
            value.get("read").is_some(),
            "snippet must define `read` key"
        );
        let rules = value
            .get("_semantex_rules")
            .and_then(|v| v.as_str())
            .expect("rules body present");
        for tool in tools.iter().filter(|t| t.live) {
            assert!(rules.contains(tool.name), "rules missing `{}`", tool.name);
        }
    }
}
