//! Codex `AGENTS.md` formatter.
//!
//! Codex picks up agent instructions from a project-root `AGENTS.md`. We
//! emit a self-contained markdown snippet that an operator can either drop
//! in directly or paste into an existing `AGENTS.md`.

use crate::skills::SKILL_INTRO;
use crate::skills::tools::ToolMetadata;

pub fn render(tools: &[ToolMetadata]) -> String {
    let mut out = String::new();
    out.push_str("# AGENTS.md — semantex section\n\n");
    out.push_str(concat!(
        "<!-- Generated by `semantex skills-generate`. Append the section below to your ",
        "project's AGENTS.md, or use this file directly as AGENTS.md. -->\n\n",
    ));

    out.push_str("## semantex — semantic code search\n\n");
    out.push_str(SKILL_INTRO);
    out.push_str("\n\n");
    out.push_str(concat!(
        "Use `semantex_agent` as the primary tool for any code search question. It auto-routes ",
        "to the right strategy and returns a complete answer in one call, saving the O(N^2) ",
        "context cost of repeated grep + read loops.\n\n",
    ));

    out.push_str("### Tools\n\n");
    out.push_str(&super::render_tools_md(tools));

    out.push_str("### Fallbacks\n\n");
    out.push_str(concat!(
        "- `Grep` / shell `rg`: exact regex on file content only — no semantic understanding.\n",
        "- `Glob`: find files by name/path pattern only.\n",
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::skills::tools::all_tools;

    #[test]
    fn renders_markdown_with_sections() {
        let tools = all_tools();
        let out = render(&tools);
        assert!(!out.trim().is_empty());
        assert!(out.starts_with("# "));
        assert!(out.contains("## semantex"));
        assert!(out.contains("### Tools"));
        for tool in &tools {
            assert!(out.contains(tool.name), "missing tool `{}`", tool.name);
        }
    }
}
