//! Devin Desktop (formerly Windsurf) rules formatter.
//!
//! Cognition acquired Windsurf and rebranded it "Devin Desktop" on
//! 2026-06-02; the old Cascade agent was EOL'd 2026-07-01. Rule files
//! carried the same on-disk conventions forward for back-compat:
//! workspace rules live under `.devin/rules/*.md` (new preferred location,
//! 12,000-char limit per file) or the legacy `.windsurf/rules/*.md` /
//! `.windsurfrules` (still read; `.devin/` wins if both exist). Both
//! locations require a `trigger:` frontmatter field
//! (`always_on` | `model_decision` | `glob` | `manual`) — a bare markdown
//! file with no frontmatter is not honored.

use crate::skills::SKILL_INTRO;
use crate::skills::tools::ToolMetadata;

pub fn render(tools: &[ToolMetadata]) -> String {
    let mut out = String::new();
    out.push_str("---\ntrigger: always_on\n---\n\n");
    out.push_str("# semantex — semantic code search\n\n");
    out.push_str("<!-- Generated by `semantex skills-generate`. -->\n\n");
    out.push_str(SKILL_INTRO);
    out.push_str("\n\n");
    out.push_str(concat!(
        "Whenever you would otherwise chain grep + read, prefer the `semantex_agent` MCP tool. ",
        "One call replaces 5–10 iterations and avoids the O(N^2) context cost of repeated ",
        "tool turns.\n\n",
    ));
    out.push_str("## Tools\n\n");
    out.push_str(&super::render_tools_md(tools));
    out.push_str("## Fallbacks\n\n");
    out.push_str(concat!(
        "- Native search: only for exact regex matches that semantex cannot bridge.\n",
        "- File browser: only when you need a path you don't know how to describe.\n",
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::skills::tools::all_tools;

    #[test]
    fn renders_markdown_with_frontmatter_and_sections() {
        let tools = all_tools();
        let out = render(&tools);
        assert!(out.starts_with("---\ntrigger: always_on\n---\n"));
        assert!(out.contains("# semantex"));
        assert!(out.contains("## Tools"));
        for tool in tools.iter().filter(|t| t.live) {
            assert!(out.contains(tool.name), "missing tool `{}`", tool.name);
        }
    }
}
