//! Trae `trae-rules.md` formatter.
//!
//! The exact agent-rules schema for Trae has not stabilised at the time of
//! writing. We emit a sensible markdown rules document covering the same
//! tool metadata as the other platforms; an operator can adjust the
//! filename or format if Trae's loader changes.

use crate::skills::SKILL_INTRO;
use crate::skills::tools::ToolMetadata;

pub fn render(tools: &[ToolMetadata]) -> String {
    let mut out = String::new();
    out.push_str("# semantex — semantic code search rules for Trae\n\n");
    out.push_str(concat!(
        "<!-- Generated by `semantex skills-generate`. Best-effort format — refine once Trae ",
        "publishes a stable agent-rules schema. -->\n\n",
    ));
    out.push_str(SKILL_INTRO);
    out.push_str("\n\n");
    out.push_str(concat!(
        "Whenever the agent would otherwise chain grep + read, it must prefer the ",
        "`semantex_agent` MCP tool. One call replaces 5–10 iterations.\n\n",
    ));
    out.push_str("## Tools\n\n");
    out.push_str(&super::render_tools_md(tools));
    out.push_str("## Fallbacks\n\n");
    out.push_str(concat!(
        "- Regex/file-content search: only for exact patterns semantex cannot bridge.\n",
        "- File listing: only when path-based discovery is required.\n",
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::skills::tools::all_tools;

    #[test]
    fn renders_markdown_with_sections() {
        let tools = all_tools();
        let out = render(&tools);
        assert!(!out.trim().is_empty());
        assert!(out.starts_with("# "));
        assert!(out.contains("## Tools"));
        for tool in &tools {
            assert!(out.contains(tool.name), "missing tool `{}`", tool.name);
        }
    }
}
