//! Windsurf `windsurfrules.md` formatter.
//!
//! Windsurf reads workspace-level agent instructions from a
//! `windsurfrules.md` (alias `.windsurfrules`) at the project root. We emit
//! a single markdown document.

use crate::skills::SKILL_INTRO;
use crate::skills::tools::ToolMetadata;

pub fn render(tools: &[ToolMetadata]) -> String {
    let mut out = String::new();
    out.push_str("# semantex — semantic code search\n\n");
    out.push_str("<!-- Generated by `semantex skills-generate`. -->\n\n");
    out.push_str(SKILL_INTRO);
    out.push_str("\n\n");
    out.push_str(concat!(
        "Whenever you would otherwise chain grep + read, prefer the `semantex_agent` MCP tool. ",
        "One call replaces 5–10 iterations and avoids the O(N^2) context cost of repeated ",
        "tool turns.\n\n",
    ));
    out.push_str("## Tools\n\n");
    out.push_str(&super::render_tools_md(tools));
    out.push_str("## Fallbacks\n\n");
    out.push_str(concat!(
        "- Native search: only for exact regex matches that semantex cannot bridge.\n",
        "- File browser: only when you need a path you don't know how to describe.\n",
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::skills::tools::all_tools;

    #[test]
    fn renders_markdown_with_sections() {
        let tools = all_tools();
        let out = render(&tools);
        assert!(!out.trim().is_empty());
        assert!(out.starts_with("# "));
        assert!(out.contains("## Tools"));
        for tool in &tools {
            assert!(out.contains(tool.name), "missing tool `{}`", tool.name);
        }
    }
}
